package Server;

import com.itextpdf.text.*;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.IOException;
import java.io.OutputStream;
import java.util.Date;

public class MakePDF extends Document{

    private static Font catFont = new Font(Font.FontFamily.TIMES_ROMAN, 18, Font.BOLD);
    private static Font smallBold = new Font(Font.FontFamily.TIMES_ROMAN, 12, Font.BOLD);

    public void generate(OutputStream outputStream, String number, String person, String owner) {
        try {
            PdfWriter.getInstance(this, outputStream);
            this.open();
            addTitlePage(this, number, person, owner);
            this.close();
        } catch (Exception ex) {
            System.out.println("Document generation error: " + ex.getMessage());
        }
    }

    private void addTitlePage(Document document, String number, String person, String owner) throws DocumentException, IOException {
        Paragraph preface;
        Image img;

        preface = new Paragraph();
        addEmptyLine(preface, 1);

        preface.add(new Paragraph("Reservation number: " + number, catFont));
        addEmptyLine(preface, 1);

        preface.add(new Paragraph("This document entitles you to enter the movie, take it with you along with your ID card. ", smallBold));
        addEmptyLine(preface, 2);
        document.add(preface);

        preface = new Paragraph();
        img = Image.getInstance(System.getProperty("user.dir") + "/src/Utilities/exemplaryQRCode.png");
        document.add(img);
        addEmptyLine(preface, 2);

        preface.add(new Paragraph("Reservation made by " + owner + " for " + person ,smallBold));
        addEmptyLine(preface, 1);

        preface.add(new Paragraph("Reservation generated by: YourPlace.cinema, " + new Date(),smallBold));
        document.add(preface);
    }

    private void addEmptyLine(Paragraph paragraph, int number) {
        for (int i = 0; i < number; i++) {
            paragraph.add(new Paragraph(" "));
        }
    }
}
